const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, 'package.json');
const versionFilePath = path.join(__dirname, 'src/lib/version.ts');

// Read package.json
const packageJson = require(packageJsonPath);
const currentVersion = packageJson.version || '0.1.0';
const versionParts = currentVersion.split('.').map(Number);

// Increment patch version
versionParts[2] += 1;
const newVersion = versionParts.join('.');

console.log(`Bumping version from ${currentVersion} to ${newVersion}`);

// Update package.json
packageJson.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');

// Create version.ts
const versionContent = `// Auto-generated by version-bump.js
export const APP_VERSION = '${newVersion}';
export const BUILD_TIMESTAMP = '${new Date().toISOString()}';
`;

fs.writeFileSync(versionFilePath, versionContent);
console.log(`Updated ${versionFilePath}`);
